"""Merge adjacent runs with identical formatting in DOCX.

Merges adjacent <w:r> elements that have identical <w:rPr> properties.
Works on runs in paragraphs and inside tracked changes (<w:ins>, <w:del>).

Also:
- Removes rsid attributes from runs (revision metadata that doesn't affect rendering)
- Removes proofErr elements (spell/grammar markers that block merging)
- Strips lastRenderedPageBreak elements during merge (rendering hints regenerated by Word)

FIX 2026-03-24: lastRenderedPageBreak elements were blocking _consolidate_text
after being moved by _merge_run_content, causing text loss on serialization.
"""

from pathlib import Path

import defusedxml.minidom

from minidom_helpers import match_local as _match_local, find_elements as _find_elements

# Elements that are rendering hints (not content) — safe to strip during merge.
# Word regenerates these on next render.
_RENDERING_HINTS = frozenset({"lastRenderedPageBreak"})


def _is_rendering_hint(node) -> bool:
    """True if node is a non-content rendering element safe to discard."""
    if node.nodeType != node.ELEMENT_NODE:
        return False
    name = node.localName or node.tagName
    return any(_match_local(name, hint) for hint in _RENDERING_HINTS)


def _extract_all_text(root) -> str:
    """Extract all text from <w:t> elements in document order."""
    texts = []
    for t_elem in _find_elements(root, "t"):
        if t_elem.firstChild and t_elem.firstChild.data:
            texts.append(t_elem.firstChild.data)
    return "".join(texts)


def merge_runs(input_dir: str) -> tuple[int, str]:
    doc_xml = Path(input_dir) / "word" / "document.xml"

    if not doc_xml.exists():
        return 0, f"Error: {doc_xml} not found"

    try:
        dom = defusedxml.minidom.parseString(doc_xml.read_text(encoding="utf-8"))
        root = dom.documentElement

        # --- TEXT INTEGRITY: snapshot before ---
        text_before = _extract_all_text(root)

        _remove_elements(root, "proofErr")
        _strip_run_rsid_attrs(root)

        containers = {run.parentNode for run in _find_elements(root, "r")}

        merge_count = 0
        for container in containers:
            merge_count += _merge_runs_in(container)

        # --- TEXT INTEGRITY: snapshot after ---
        text_after = _extract_all_text(root)

        if text_before != text_after:
            before_len = len(text_before)
            after_len = len(text_after)
            loss_pct = (1 - after_len / before_len) * 100 if before_len else 0

            if loss_pct > 1.0:
                return 0, (
                    f"Error: text integrity check failed — "
                    f"lost {before_len - after_len} chars ({loss_pct:.1f}%). "
                    f"Before: {before_len}, After: {after_len}. "
                    f"Aborting write to prevent data loss."
                )

        doc_xml.write_bytes(dom.toxml(encoding="UTF-8"))
        return merge_count, f"Merged {merge_count} runs"

    except Exception as e:
        return 0, f"Error: {e}"


def _get_child(parent, tag: str):
    for child in parent.childNodes:
        if child.nodeType == child.ELEMENT_NODE:
            name = child.localName or child.tagName
            if _match_local(name, tag):
                return child
    return None


def _get_children(parent, tag: str) -> list:
    results = []
    for child in parent.childNodes:
        if child.nodeType == child.ELEMENT_NODE:
            name = child.localName or child.tagName
            if _match_local(name, tag):
                results.append(child)
    return results


def _is_adjacent(elem1, elem2) -> bool:
    """Check if two elements are adjacent, treating rendering hints as transparent."""
    node = elem1.nextSibling
    while node:
        if node == elem2:
            return True
        if node.nodeType == node.ELEMENT_NODE:
            # Rendering hints (e.g. lastRenderedPageBreak) don't block adjacency
            if _is_rendering_hint(node):
                node = node.nextSibling
                continue
            return False
        if node.nodeType == node.TEXT_NODE and node.data.strip():
            return False
        node = node.nextSibling
    return False


def _remove_elements(root, tag: str):
    for elem in _find_elements(root, tag):
        if elem.parentNode:
            elem.parentNode.removeChild(elem)


def _strip_run_rsid_attrs(root):
    for run in _find_elements(root, "r"):
        for attr in list(run.attributes.values()):
            if "rsid" in attr.name.lower():
                run.removeAttribute(attr.name)


def _merge_runs_in(container) -> int:
    merge_count = 0
    run = _first_child_run(container)

    while run:
        while True:
            next_elem = _next_element_sibling(run)
            if next_elem and _is_run(next_elem) and _can_merge(run, next_elem):
                _merge_run_content(run, next_elem)
                container.removeChild(next_elem)
                merge_count += 1
            else:
                break

        _consolidate_text(run)
        run = _next_sibling_run(run)

    return merge_count


def _first_child_run(container):
    for child in container.childNodes:
        if child.nodeType == child.ELEMENT_NODE and _is_run(child):
            return child
    return None


def _next_element_sibling(node):
    sibling = node.nextSibling
    while sibling:
        if sibling.nodeType == sibling.ELEMENT_NODE:
            return sibling
        sibling = sibling.nextSibling
    return None


def _next_sibling_run(node):
    sibling = node.nextSibling
    while sibling:
        if sibling.nodeType == sibling.ELEMENT_NODE:
            if _is_run(sibling):
                return sibling
        sibling = sibling.nextSibling
    return None


def _is_run(node) -> bool:
    name = node.localName or node.tagName
    return name == "r" or name.endswith(":r")


def _can_merge(run1, run2) -> bool:
    rpr1 = _get_child(run1, "rPr")
    rpr2 = _get_child(run2, "rPr")

    if (rpr1 is None) != (rpr2 is None):
        return False
    if rpr1 is None:
        return True
    return rpr1.toxml() == rpr2.toxml()


def _merge_run_content(target, source):
    """Move content children from source to target, stripping rendering hints."""
    for child in list(source.childNodes):
        if child.nodeType == child.ELEMENT_NODE:
            name = child.localName or child.tagName
            # Skip rPr (formatting — already matched)
            if name == "rPr" or name.endswith(":rPr"):
                continue
            # Strip rendering hints — they block text consolidation
            # and are regenerated by Word on next render
            if _is_rendering_hint(child):
                continue
            target.appendChild(child)


def _consolidate_text(run):
    """Merge adjacent <w:t> elements within a single run.

    Also strips any rendering hint elements that sit between <w:t> elements,
    since they would otherwise prevent consolidation.
    """
    # First pass: remove rendering hints that sit between <w:t> elements
    for hint in [ch for ch in run.childNodes if _is_rendering_hint(ch)]:
        run.removeChild(hint)

    t_elements = _get_children(run, "t")

    for i in range(len(t_elements) - 1, 0, -1):
        curr, prev = t_elements[i], t_elements[i - 1]

        if _is_adjacent(prev, curr):
            prev_text = prev.firstChild.data if prev.firstChild else ""
            curr_text = curr.firstChild.data if curr.firstChild else ""
            merged = prev_text + curr_text

            if prev.firstChild:
                prev.firstChild.data = merged
            else:
                prev.appendChild(run.ownerDocument.createTextNode(merged))

            if merged.startswith(" ") or merged.endswith(" "):
                prev.setAttribute("xml:space", "preserve")
            elif prev.hasAttribute("xml:space"):
                prev.removeAttribute("xml:space")

            run.removeChild(curr)


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("Usage: python merge_runs.py <unpacked_dir>", file=sys.stderr)
        sys.exit(1)

    count, msg = merge_runs(sys.argv[1])
    print(msg)
    sys.exit(0 if "Error" not in msg else 1)
